// Demo mode: when VITE_DEMO=1, the app bypasses auth and serves in-memory sample
// data instead of hitting Supabase. Lets you preview the UI before the backend is
// wired up. Has zero effect in production (VITE_DEMO is unset on Netlify).
import type { Application, ApplicationNote } from './types';

export const DEMO = import.meta.env.VITE_DEMO === '1';

const now = '2026-06-21T18:00:00Z';
const earlier = '2026-06-20T15:00:00Z';

const SAMPLE_RESUME = `# Spencer Quinn — GTM Strategy & Operations

**Account Executive, AI Native — Anthropic**

AI-native operator and founder with 15+ years scaling revenue orgs to $80M+, now building
hands-on with Claude Code and the Anthropic API. I sell the way Anthropic builds: technical
credibility plus commercial rigor.

## Selected impact
- CEO, Merch Makers AI — $50M+ GMV; built & shipped agentic AI software to production.
- Director, Biolite/Goal Zero — 33% YoY growth; $80M+ Shopify + Amazon sales ops.
- Optimize Play — led $22M GTM across Target/Walmart/Amazon; raised $100M+ via crowdfunding.

*(Full draft generated by the job-hunter agent — editable here before you apply.)*`;

const SAMPLE_COVER = `Dear Anthropic team,

The "AI Native" in this role is the part of my story I'm most excited about. I'm not a seller who
picked up AI talking points last quarter — I've spent the last two years building agentic software on
Claude Code and the Anthropic API, and teaching 50+ people to build with LLMs. I can sit across from a
technical buyer and be genuinely useful.

I've carried real number-bags before: $50M+ GMV as a founder-CEO, $80M+ in sales ops at Biolite/Goal
Zero, $22M in GTM negotiations across Target, Walmart, and Amazon. I know how to run a deliberate,
consultative motion and translate a customer's messy reality into a deployment that sticks.

I'd love to talk about how I'd open and close AI-native accounts for Anthropic.

Spencer Quinn`;

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: 'demo-1', company: 'Anthropic', role_title: 'Account Executive, AI Native',
    job_url: 'https://job-boards.greenhouse.io/anthropic/jobs/4461450008',
    location: 'San Francisco, CA | New York City, NY', team: 'Sales', fit_score: 82,
    status: 'Ready for Review', source: 'agent', created_at: earlier, updated_at: now,
    greenhouse_id: 4461450008, salary_range: null,
    job_description: 'Anthropic is looking for an Account Executive to drive adoption of Claude across AI-native companies...',
    fit_summary: 'Strong fit — blends technical AI credibility with a proven $80M+ commercial track record. GTM/AE motion maps directly to his founder + ecommerce-ops background. Voice: startup-partnerships.',
    tailored_resume: SAMPLE_RESUME, cover_letter: SAMPLE_COVER,
  },
  {
    id: 'demo-2', company: 'Anthropic', role_title: 'Startup Programs Lead',
    job_url: 'https://job-boards.greenhouse.io/anthropic/jobs/5101378008',
    location: 'San Francisco, CA', team: 'Go-To-Market', fit_score: 88,
    status: 'Ready for Review', source: 'agent', created_at: earlier, updated_at: earlier,
    greenhouse_id: 5101378008, salary_range: null,
    job_description: 'Lead programs that bring frontier AI to early-stage founders...',
    fit_summary: 'Excellent fit — he IS a seed-stage AI founder right now, with firsthand ecosystem perspective. Voice: startup-partnerships.',
    tailored_resume: SAMPLE_RESUME, cover_letter: SAMPLE_COVER,
  },
  {
    id: 'demo-3', company: 'Pattern', role_title: 'Fractional Head of RevOps',
    job_url: 'https://example.com/pattern-fractional-revops',
    location: 'Lehi, UT (hybrid)', team: null, fit_score: 91,
    status: 'Discovered', source: 'agent', created_at: now, updated_at: now,
    greenhouse_id: null, salary_range: null,
    job_description: 'Part-time/fractional RevOps leader for a Utah growth-stage company...',
    fit_summary: 'Top preference — fractional + Utah (+20 bump) and squarely in his RevOps wheelhouse. Queued for drafting.',
    tailored_resume: null, cover_letter: null,
  },
  {
    id: 'demo-4', company: 'Recursion', role_title: 'Fractional AI Advisor',
    job_url: 'https://example.com/recursion-ai-advisor',
    location: 'Salt Lake City, UT', team: null, fit_score: 84,
    status: 'Applied', source: 'manual', created_at: earlier, updated_at: now,
    greenhouse_id: null, salary_range: '$150–250/hr',
    job_description: 'Advisory engagement helping a Utah team operationalize LLM workflows...',
    fit_summary: 'Fractional + Utah + AI enablement — matches his American Heritage/Between Prompts work. You added this one.',
    tailored_resume: SAMPLE_RESUME, cover_letter: SAMPLE_COVER,
  },
];

export const DEMO_NOTES: Record<string, ApplicationNote[]> = {
  'demo-4': [
    {
      id: 'n1', application_id: 'demo-4', author_email: 'espencer.quinn@gmail.com',
      author_name: 'Spencer', body: 'Applied 6/21. Warm intro via MIT xPRO network — following up Monday.',
      created_at: now,
    },
  ],
};
